<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(DotNetTarget)</TargetFramework>
        <RootNamespace>MelonLoader.Support</RootNamespace>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <OutputPath>$(MLOutDir)/MelonLoader/Dependencies/SupportModules</OutputPath>
        <DebugType>embedded</DebugType>
        <DefineConstants>SM_Il2Cpp</DefineConstants>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="Il2CppInterop.HarmonySupport" Condition="'$(TargetFramework)' == '$(DotNetTarget)'">
          <HintPath>..\..\..\..\Il2CppInterop\Il2CppInterop.HarmonySupport\bin\Debug\net10.0\Il2CppInterop.HarmonySupport.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppInterop.Initialization" Condition="'$(TargetFramework)' == '$(DotNetTarget)'">
          <HintPath>..\..\..\..\..\..\..\home\ati\.local\share\Steam\steamapps\common\Slime Rancher 2\MelonLoader\Il2CppAssemblies\Il2CppInterop.Initialization.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppInterop.Runtime" Condition="'$(TargetFramework)' == '$(DotNetTarget)'">
          <HintPath>..\..\..\..\Il2CppInterop\Il2CppInterop.HarmonySupport\bin\Debug\net10.0\Il2CppInterop.Runtime.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppInterop.Common" Condition="'$(TargetFramework)' == '$(DotNetTarget)'">
          <HintPath>..\..\..\..\Il2CppInterop\Il2CppInterop.HarmonySupport\bin\Debug\net10.0\Il2CppInterop.Common.dll</HintPath>
        </Reference>
        <Reference Include="Il2Cppmscorlib">
            <HintPath>Libs\Il2Cppmscorlib.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Il2CppSystem">
            <HintPath>Libs\Il2CppSystem.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>Libs\UnityEngine.CoreModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <Compile Include="..\Component.cs" Link="Component.cs" />
        <Compile Include="..\ComponentSiblingFix.cs" Link="ComponentSiblingFix.cs" />
        <Compile Include="..\SupportModule_To.cs" Link="SupportModule_To.cs" />
        <Compile Include="..\SceneHandler.cs" Link="SceneHandler.cs" />
        <Compile Include="..\UnityMappers.cs" Link="UnityMappers.cs" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="$(SolutionDir)\MelonLoader\MelonLoader.csproj" Private="false" />
        <PackageReference Include="AssetRipper.Primitives" Version="$(AssetRipperVersion)" ExcludeAssets="Runtime" />
        <PackageReference Include="HarmonyX" Version="$(HarmonyXVersion)" ExcludeAssets="Runtime" />
        <PackageReference Include="Iced" Version="$(IcedVersion)" ExcludeAssets="Runtime" />
        <PackageReference Include="Mono.Cecil" Version="$(MonoCecilVersion)" ExcludeAssets="Runtime" />
        <PackageReference Include="MonoMod.RuntimeDetour" Version="$(MonoModRuntimeDetour)" ExcludeAssets="Runtime" />
        <PackageReference Include="MonoMod.Utils" Version="$(MonoModUtils)" ExcludeAssets="Runtime" />
        <PackageReference Include="Samboy063.Tomlet" Version="$(TomletVersion)" ExcludeAssets="Runtime" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0.0"/>
    </ItemGroup>
</Project>
